script: npm run deploy
language: node_js
node_js:
- '6'
env:
  global:
  - GH_REF: github.com/websemantics/pyrocms-cheatsheet.git
  - secure: Ncc/kpcl5XVj6QVFWNIZMnoHljmcRmxoj0HKkPMM0LGtoYRubCNaT5VORu0kqbY47rhglk+8WbX6JdlRBszIVhXdEnbzeslCF3aQPHWheIWgkgqQog23cTqTIfbpaXOEm5nqiIKnYgg3u+7W1peNQdU8xAuzJyef7+u/1B8nWXlhZ3P58b8ganRzDcPfowEWnRg3/Hjh2YYuSVpsCl4SVTG5J9xcQ+nt3+pZB+ft5bbB6ARKc6yw2askPZdWRbIs6vjn9vOUZDQ+0mMQM/JX7rqfwRmmQ2sKlHlQ1/i0aWXBAYfjGrC1T2NfnYodJ2tcDH4G3KBZLlfwMBfXKS/Mhu3ACf+XolTpeRSaOEUJ1bRyUk6oQkm2iDi/QpYyR7V8+u0UuxxbGGkZXM7VtFpVPKHzog1Rz/jtaMasvQ6Xkwwxmsb6u6FF/xMari53WuiyXsFfhnF1Hzl4NZkbEiFMBmjDEtUVH58A5/klcPmnI1IZ5ce00M3ScKXBI1UNSWjDYhJ15IZ9g7yyyst9aj/+YC5N+4mwDv2J3XIRSXfuf6xkpe3cWnVzVZsCRaSTsa9z5megkIU/BjDaFBHhATalyHr3G6+j2AVQmFEbAnev6UNiOcf5iCTmCIqCBNCi2xlKNXKB0lS2S1k6x0unLZBd/GOXkym6uqVYaaXoXjPIhTU=
